name: Windows Deployment Workflow

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - run: npm run build
    - uses: cloudflare/pages-action@v1
    with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: nextra-test-cloudflare
          directory: build/client

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.12.0'